### ISSUE TITLE
[Enhancement] Parser to find multiple ROM types

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#21]
I was setting a up a configuration and I was trying to figure out how to have multiple ROM types in the User's Glob. There are a few different emulators that accept different types of ROM file types. In my ROM library I have multiple ROM types (file types/extension). Do I have to make a different config file for each type of ROM within the same system emulator or can you add the ability to have the parser to look for different ROM file types in a ROM directory. Thanks!
Example:
nickname=Dreamcast
emulator=nulldc
extensions=gdi, cdi
roms directory=E:\emulation\roms\dreamcast

**Comment by FrogTheFrog** [comment]
`node-glob` has patterns for this purpose and somehow I forgot to implement them. Will try to look at it once I'm free.

**Comment by FrogTheFrog** [comment]
@HEspoke Check out the new `2.1.0` branch. It has new patterns implemented. Now you can do this: `${title}.@(gdi|cdi)` or `${title}.@([gc]di)` or something similar.

From changelog:
* Proper `node-glob` patterns support for `glob` and `glob-regex` parsers:
    * `*` Matches 0 or more characters in a single path portion.
    * `?` Matches 1 character.
    * `[...]` Matches a range of characters, similar to a RegExp range. If the first character of the range is `!` or `^` then it matches any character not in the range.
    * `!(pattern|pattern|pattern)` Matches anything that does not match any of the patterns provided.
    * `?(pattern|pattern|pattern)` Matches zero or one occurrence of the patterns provided.
    * `+(pattern|pattern|pattern)` Matches one or more occurrences of the patterns provided.
    * `*(a|b|c)` Matches zero or more occurrences of the patterns provided.
    * `@(pattern|pat*|pat?erN)` Matches exactly one of the patterns provided
    * `**` If a "globstar" is alone in a path portion, then it matches zero or more directories and subdirectories searching for matches. It does not crawl symlinked directories.

**Comment by HEspoke** [comment]
I think I am overlooking something here. I am getting "Failed to Match" Errors

Testing "Dreamcast" parser.
 
Failed to match:
[1/7]: E:\emulation\roms\dreamcast\Daytona USA.CDI
[2/7]: E:\emulation\roms\dreamcast\Jet Grind Radio\Jet Grind Radio.gdi
[3/7]: E:\emulation\roms\dreamcast\San Fransico Rush 2049.CDI
[4/7]: E:\emulation\roms\dreamcast\Soul Calibur\Soul Calibur.gdi
[5/7]: E:\emulation\roms\dreamcast\Star Wars Demolition.CDI
[6/7]: E:\emulation\roms\dreamcast\Star Wars Episode I Racer\Star Wars Episode I Racer.CUE
[7/7]: E:\emulation\roms\dreamcast\Street Fighter Alpha 3\Street Fighter Alpha 3 Dreamcast.gdi
 
"Dreamcast" parser test is completed.


![image](https://user-images.githubusercontent.com/26511314/27518307-d65f12ac-59aa-11e7-8426-020b0e10526a.png)

**Comment by FrogTheFrog** [comment]
@HEspoke Sorry, had a busy day today so I tried it to push A.S.A.P. and totally forgot about one little bug. Should be working now. Also, Steam directory is incorrect. It must be a Steam directory, not userdata directory. User accounts are optional, but if you want to specify them you must use `${username}` syntax, where username is your name that you use to log in into steam.

**Comment by HEspoke** [comment]
I noticed that your commit was for a regex bug. Am i supposed to be using Glob Regex instead of Glob for this to work correctly? I updated my directory to match your most recent update and I am still getting the errors. Thanks for working with me. I enjoy troubleshooting

![image](https://user-images.githubusercontent.com/26511314/27519244-6d7aa4be-59bd-11e7-89fd-fa21b955b92d.png)


![image](https://user-images.githubusercontent.com/26511314/27519225-18cab6e8-59bd-11e7-8c96-30d9c6741400.png)

Edit: fixed my error in "Steam Category" . Now is `${Sega Dreamcast}`  but problem stated above still persist

**Comment by FrogTheFrog** [comment]
@HEspoke This is strange. I tried reproducing this error with same directory structure as yours, but it works for me. I have fixed "depth" bug for both parsers, maybe this will fix it? Anyway, what sort of IDE are you using? `vscode`perhaps?

**Comment by HEspoke** [comment]
@FrogTheFrog  yes VSCode   . Question: Where are the config files saved for each emulator so that I can back them up

**Comment by FrogTheFrog** [comment]
@HEspoke Should be in `AppData\Roaming\Electron\userData`. To debug via Vscode you need to have `Debugger for Chrome` installed. Then run `watch:renderer` and launch app via `Debug Main`. Ctrl+R will reload main app and you will not need to restart debugger in case you change some files. Run `Debug Renderer` to enable breakpoints (they are broken after latest vscode update and will only start working after you at least add one breakpoint after renderer has launched. This includes refreshing with Ctrl+R) and `debug console`.

Now, can you go to line 247 in `glob.parser.ts` and find out why `extractTitle` returns `undefined`?

**Comment by HEspoke** [comment]
@FrogTheFrog Honestly, I am not experienced in debugging or actually writing code in this language. I deleted everything and then rebuilt the program from scratch and now it is finding my roms. 
I must say, this program is exactly what I hoped ICE would turn into. I hope that I can help you with testing the program and help give you feed back to make it better. GREAT JOB.
I have a lot of experience with ICE and working out all of the command line executable arguments in order to get a seamless experience with running all of these emulators with only a controller from Big Picture Mode. I saw on reddit that you are looking for those arguments so that you can build in those arguments as preset option for different emulators. When I am done testing, I will be happy to gradually pass those along to you.

Right now the only problem I have is that when SRM is building the database it has a big problem with timing out when looking for the Steam Grid image. I dont think it is a problem with your program but rather the website that is serving your program the images. I am not sure what can be done about that but I will post a image of what I am talking about. The message in the bottom right keeps popping up and most of the images never end up populating.

<img width="860" alt="2017-06-25 20_44_01-steam rom manager" src="https://user-images.githubusercontent.com/26511314/27521535-10326308-59ec-11e7-8158-5fb6836613a7.png">

You can close this Enhancement thread whenever you want as a success. Thanks!

**Comment by FrogTheFrog** [comment]
@HEspoke Thank you. Those arguments for presets would be great! Eventually I will implement some sort of argument wizard, that would help to construct final argument string. Finally, I can't really do anything about retrogaming.cloud, but the owner promised he would create a new API which would reduce the amount of timeouts.
